### PR TITLE
Certbund import

### PR DESCRIPTION
**Pull request by rolandgeider**
This is a PR for the import script for the RIPE and ASN files into the certBUND database.

@bernhard-herzog: much of the code was written @gsiv and me together. Since I won't be in the office for the next days I won't be able to perform any changes, but might be able to answer some questions.

### CODE REVIEW

**Comment by aaronkaplan** [comment]
hey, folks... wait a bit . I still have some schema changes to propose!

**Comment by dmth** [comment]
> Did Dustin forward you my proposal s I discussed with him?
Yes I shared that with bernhard-herzog, although it might have been a bit late. We figured out that whilst doing the import-scripts we came up with an idea similar to your "shadow-tables". It is very good that this concept was developed from two teams independently, as this might show that it is a reasonable way to go for all teams!

**Comment by aaronkaplan** [comment]
Perfect. No problem. I'll send a PR with the new proposed schema. Let's still double check that it really fits our needs and then I think we are ready to go.

**Comment by aaronkaplan** [comment]
just a comment, actually I sent the PR (just to the master branch). So, my side seems done.

**Pull request merged**
